### ISSUE TITLE
UDP status don't get updated after recover from OFFLINE.

### ISSUE THREAD

**Issue by jackyyf** [Tox/ToxStatus#17]
One of my tox-bootstrapd got offline due to hardware failure. But even I've recovered the server, server is still identified as ONLINE with only TCP relay.

I've checked with `DHT_bootstrap` program shipped with toxcore with TCP disabled, it shows UDP actually works.

**Comment by jackyyf** [comment]
For more information if needed, the server listed on `nodes.tox.chat` is `hibiki.eve.moe`, maintained by me.

**Comment by abbat** [comment]
I have the same problem. How many IPv6 you assign to one interface? Seems ToxStatus server compare node IPv6 in outgoing packet and incoming, but if host has more than one IPv6 address on same interface it can send reply from another source address (typically last added address). See [RFC-3484, "Default Address Selection for Internet Protocol version 6"](http://www.rfc-editor.org/rfc/rfc3484.txt) for details.

P.S. Temporary workaround is to set `preferred_lft 0` when configuring interfaces like [here](http://www.davidc.net/networking/ipv6-source-address-selection-linux)

**Comment by nurupo** [comment]
@abbat this sounds like a toxcore issue. Your node's toxcore receives a get-nodes request from nodes.tox.chat on one IPv6, but sends a get-nodes reply back through a different IPv6. Instead it should have sent the get-nodes reply back using the same IPv6 address it received the request on. nodes.tox.chat has no knowledge that both IPv6 addresses belong to the node, so it can't associate the reply received from.

**Comment by abbat** [comment]
@nurupo What about to determine node by request/reply public key and request id - it equals in outgoing and incoming packets even if two nodes with same keypair exists and send replies in some time.

**Comment by jackyyf** [comment]
@abbat I have same issue for multiple IPv4/IPv6 address on primary device, and I solved it by create a separate network namespace, assign a static IPv4/IPv6 for it (of course you can assign a private IPv4 and enable NAT on global network namespace if you are short of dedicate IPv4 address), and start tox-bootstrapd inside.
DO NOTE that if you use a locally cached name server, you must launch a separate instance inside the namespace, since inside the namespace it can not connect to socket outside the namespace. 

Part of my configuration and systemd service files:
https://gist.github.com/jackyyf/60d9c47d334eb34b6acc4c41beceec72

**Comment by alexbakker** [comment]
I'm currently test-driving the 'rework' branch at https://nodes.tox.chat/beta. It doesn't look at IP addresses of the sendnodes responses anymore, just the public keys. So if this still happens there, it's probably a toxcore issue.
