### ISSUE TITLE
The web app gets stuck after some time

### ISSUE THREAD

**Issue by alexbakker** [Tox/ToxStatus#18]
My best guess is that the http.Get call that is made to grab the nodes from the wiki causes this issue. This probably happens because the default http client doesn't have a timeout.

**Comment by alexbakker** [comment]
Well, fbfc025 didn't fix it.

**Comment by nurupo** [comment]
Can't you just run a debug copy of it and analyse its state once it gets stuck?

**Comment by alexbakker** [comment]
This issue was probably fixed by 8ad7beba3835373757f0b19f8999644a63592d1b. Closing for now.
