### ISSUE TITLE
Drop-down layout

### ISSUE THREAD

**Issue by Zer0-One** [Tox/ToxStatus#3]
Items in the drop-downs should be layed out horizontally before vertically. Currently, there's a lot of wasted space.

**Comment by alexbakker** [comment]
I wouldn't know how to make that look good. Especially with varying MOTD lengths.

**Comment by alexbakker** [comment]
Actually I guess 7809310fe9ba1fd09cc231e24abb52809e105010 does the trick.
Please reopen if you disagree.
