### ISSUE TITLE
Display the country of the server/IP directly in table view with a flag

### ISSUE THREAD

**Issue by rugk** [Tox/ToxStatus#6]
I think displaying the country of the server would be nice.

So you can see that the nodes are (hopefully) spread in multiple different countries across the world.

**Comment by rugk** [comment]
Okay, just saw that you can click on it and see it, but IMO a flag would be nicer for indicating the country. A flag icon would allow it to be seen at the first glance.

**Comment by alexbakker** [comment]
I agree, I'll see if I can add some flags.

**Comment by rugk** [comment]
Now https://nodes.tox.chat/ returns a 503 error. :cry:

**Comment by alexbakker** [comment]
Yep, some trouble rebuilding the docker image apparently.
Should be fine now!

**Comment by rugk** [comment]
It works. ANd it looks very nice! :smiley: 
Thanks for fixing this so fast.
